# uncompyle6 version 3.9.3
# Python bytecode version base 2.6 (62161)
# Decompiled from: Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
# Embedded file name: scripts/common/constants.py
# Compiled at: 2011-06-28 18:13:04
try:
    import BigWorld
except:
    IS_CLIENT = False
    IS_CELLAPP = False
    IS_BASEAPP = True
    IS_WEB = IS_BASEAPP
else:
    IS_CLIENT = BigWorld.component == 'client'
    IS_CELLAPP = BigWorld.component == 'cell'
    IS_BASEAPP = not (IS_CLIENT or IS_CELLAPP)
    IS_WEB = IS_BASEAPP

DEFAULT_LANGUAGE = 'en'
IS_DEVELOPMENT = False
IS_CHINA = False
SHOW_LANGUAGE_BAR = False
IS_SHOW_SERVER_STATS = not IS_CHINA
IS_CAT_LOADED = False
SERVER_TICK_LENGTH = 0.1
SHELL_TRAJECTORY_EPSILON_CLIENT = 0.03
SHELL_TRAJECTORY_EPSILON_SERVER = 0.1
ARENA_TYPE_XML_PATH = 'scripts/arena_defs/'
ITEM_DEFS_PATH = 'scripts/item_defs/'
SPACE_DATA_ITEMS_VISIBILITY_MASK = 300
VOICE_CHAT_INIT_TIMEOUT = 10

class DESTRUCTIBLE_MATKIND:
    MIN = 71
    MAX = 100
    NORMAL_MIN = 73
    NORMAL_MAX = 86
    DAMAGED_MIN = 87
    DAMAGED_MAX = 100


class DOSSIER_TYPE:
    ACCOUNT = 1
    VEHICLE = 2
    TANKMAN = 4


class ARENA_GUI_TYPE:
    UNKNOWN = 0
    RANDOM = 1
    TRAINING = 2
    COMPANY = 3
    RANGE = (
     UNKNOWN, RANDOM, TRAINING, COMPANY)


class ARENA_BONUS_TYPE:
    UNKNOWN = 0
    REGULAR = 1
    TRAINING = 2
    COMPANY = 3
    TOURNAMENT = 4
    CLAN = 5
    RANGE = (
     UNKNOWN, REGULAR, TRAINING, COMPANY, TOURNAMENT, CLAN)


class ARENA_PERIOD:
    WAITING = 1
    PREBATTLE = 2
    BATTLE = 3
    AFTERBATTLE = 4


class ARENA_UPDATE:
    VEHICLE_LIST = 1
    VEHICLE_ADDED = 2
    PERIOD = 3
    STATISTICS = 4
    VEHICLE_STATISTICS = 5
    VEHICLE_KILLED = 6
    AVATAR_READY = 7
    BASE_POINTS = 8
    BASE_CAPTURED = 9
    TEAM_KILLER = 10


class JOIN_FAILURE:
    TIME_OUT = 1
    NOT_FOUND = 2
    ACCOUNT_LOCK = 3
    WRONG_VEHICLE = 4
    TEAM_IS_FULL = 5
    WRONG_ARGS = 6
    CAPTCHA = 7
    ARENA_IS_NOT_RUNNING = 8
    CANNOT_CREATE = 9
    PRIVACY = 10
    WRONG_ACCOUNT_TYPE = 11
    COOLDOWN = 12


JOIN_FAILURE_NAMES = dict([_[1] for (k, v) in JOIN_FAILURE.__dict__.iteritems() if not k.startswith('_')])

class KICK_REASON:
    ARENA_CREATION_FAILURE = 1
    AVATAR_CREATION_FAILURE = 2
    VEHICLE_CREATION_FAILURE = 3
    PREBATTLE_CREATION_FAILURE = 4
    BASEAPP_CRASH = 5
    CELLAPP_CRASH = 6
    UNKNOWN_FAILURE = 7
    FINISHED = 8
    CREATOR_LEFT = 9
    PLAYERKICK = 10
    TIMEOUT = 11


KICK_REASON_NAMES = dict([_[2] for (k, v) in KICK_REASON.__dict__.iteritems() if not k.startswith('_')])

class FINISH_REASON:
    UNKNOWN = 0
    EXTERMINATION = 1
    BASE = 2
    TIMEOUT = 3
    FAILURE = 4
    TECHNICAL = 5


class PREBATTLE_TYPE:
    SQUAD = 1
    TRAINING = 2
    COMPANY = 3
    TOURNAMENT = 4
    CLAN = 5
    RANGE = (
     SQUAD, TRAINING, COMPANY, TOURNAMENT, CLAN)


class PREBATTLE_START_TYPE:
    DIRECT = 1
    SQUAD = 2
    COMPANY = 3
    RANGE = (
     DIRECT, SQUAD, COMPANY)


class PREBATTLE_ROLE:
    TEAM_READY_1 = 1
    TEAM_READY_2 = 2
    ASSIGNMENT_1 = 4
    ASSIGNMENT_2 = 8
    ASSIGNMENT_1_2 = 16
    SEE_1 = 32
    SEE_2 = 64
    KICK_1 = 512
    KICK_2 = 1024
    CHANGE_ARENA = 2048
    CHANGE_COMMENT = 4096
    OPEN_CLOSE = 8192
    INVITE = 16384
    CHANGE_ARENA_VOIP = 32768
    TRAINING_DEFAULT = SEE_1 | SEE_2
    TRAINING_CREATOR = TRAINING_DEFAULT | TEAM_READY_1 | TEAM_READY_2 | ASSIGNMENT_1 | ASSIGNMENT_2 | ASSIGNMENT_1_2 | KICK_1 | KICK_2 | CHANGE_ARENA | CHANGE_COMMENT | OPEN_CLOSE | INVITE | CHANGE_ARENA_VOIP
    SQUAD_DEFAULT = SEE_1
    SQUAD_CREATOR = SQUAD_DEFAULT | TEAM_READY_1 | KICK_1 | INVITE
    COMPANY_DEFAULT = SEE_1
    COMPANY_CREATOR = COMPANY_DEFAULT | TEAM_READY_1 | ASSIGNMENT_1 | KICK_1 | CHANGE_COMMENT | OPEN_CLOSE | INVITE


class PREBATTLE_STATE:
    IDLE = 0
    IN_QUEUE = 1
    IN_BATTLE = 2


class PREBATTLE_TEAM_STATE:
    NOT_READY = 1
    READY = 2
    LOCKED = 3


class PREBATTLE_ACCOUNT_STATE:
    UNKNOWN = 0
    NOT_READY = 1
    AFK = 2 | NOT_READY
    READY = 4
    IN_BATTLE = 8
    OFFLINE = 16


PREBATTLE_COMMENT_MAX_LENGTH = 400

class PREBATTLE_UPDATE:
    ROSTER = 1
    PLAYER_ADDED = 2
    PLAYER_REMOVED = 3
    PLAYER_STATE = 4
    PLAYER_ROSTER = 5
    TEAM_STATES = 6
    SETTINGS = 7
    SETTING = 8
    KICKED_FROM_QUEUE = 9
    PROPERTIES = 10
    PROPERTY = 11


class PREBATTLE_CACHE_KEY:
    TYPE = 1
    IS_OPENED = 2
    STATE = 3
    IS_FULL = 4
    PLAYER_COUNT = 5
    CREATOR = 6
    CREATE_TIME = 7
    START_TIME = 8
    COMMENT = 9
    DESCRIPTION = 10
    ARENA_TYPE_ID = 11
    ROUND_LENGTH = 12
    CREATOR_CLAN_DB_ID = 14
    CREATOR_CLAN_ABBREV = 15


class PREBATTLE_COMPANY_LIMIT:
    TOTAL_LEVEL_MIN = 70
    TOTAL_LEVEL_MAX = 90


class ACCOUNT_TYPE:
    BASE = 0
    PRESENTATION = 1
    SUPPORTER = 2
    DEMO = 3
    DEVELOPER = 4
    RANGE = (
     BASE, PRESENTATION, SUPPORTER, DEMO, DEVELOPER)


class ACCOUNT_ATTR:
    BATTLE_XP = 1
    TRADING = 2
    CLAN = 4
    MERCENARY = 8
    RATING = 16
    USER_INFO = 32
    STATISTICS = 64
    ARENA_CHANGE = 128
    CHAT_ADMIN = 256
    ADMIN = 512
    ROAMING = 1024
    DAILY_BONUS_1 = 2097152
    DAILY_BONUS_2 = 4194304
    ALPHA = 536870912
    CBETA = 1073741824
    OBETA = 2147483648L
    PREMIUM = 4294967296L
    AOGAS = 8589934592L
    INNER_RANGE = (
     PREMIUM,)


class RESTRICTION_TYPE:
    NONE = 0
    BAN = 1
    BAN_AFTER_BATTLE = 2
    CHAT_BAN = 3
    TRADING = 4
    CLAN = 5


class RESTRICTION_SOURCE:
    UNKNOWN = 0
    SERVER = 1
    CLIENT = 2
    BACKYARD = 3
    MIGRATOR = 4


class CLAN_MEMBER_FLAGS(object):
    LEADER = 1
    VICE_LEADER = 2
    RECRUITER = 4
    TREASURER = 8
    DIPLOMAT = 16
    COMMANDER = 32
    PRIVATE = 64
    RECRUIT = 128
    MAY_ADD_MEMBERS = LEADER | VICE_LEADER | RECRUITER
    MAY_REMOVE_MEMBERS = LEADER | VICE_LEADER | RECRUITER
    MAY_CHANGE_MEMBER_FLAGS = LEADER | VICE_LEADER
    MAY_TRADE = LEADER | VICE_LEADER | TREASURER


class AUTO_AIM_LOSS_REASON:
    TOO_FAR = 1
    INVISIBLE = 2
    KILLED = 3


class AIMING_MODE:
    SHOOTING = 1
    TARGET_LOCK = 16
    USER_DISABLED = 256


class VEHICLE_SETTING:
    CURRENT_SHELLS = 0
    NEXT_SHELLS = 1
    AUTOROTATION_ENABLED = 2
    ACTIVATE_EQUIPMENT = 16


class DEVELOPMENT_INFO:
    ATTACK_RESULT = 1
    FIRE_RESULT = 2
    BONUSES = 3
    VISIBILITY = 4


class SHOT_RESULT:
    RICOCHET = 0
    ARMOR_NOT_PIERCED = 1
    ARMOR_PIERCED_NO_DAMAGE = 2
    ARMOR_PIERCED = 3
    CRITICAL_HIT = 4
    MIN_HIT = ARMOR_PIERCED
    MAX_HIT = CRITICAL_HIT


DAMAGE_INFO_CODES = ('DEVICE_CRITICAL', 'DEVICE_DESTROYED', 'TANKMAN_HIT', 'FIRE',
                     'DEVICE_CRITICAL_AT_SHOT', 'DEVICE_CRITICAL_AT_RAMMING', 'DEVICE_DESTROYED_AT_SHOT',
                     'DEVICE_DESTROYED_AT_RAMMING', 'DEVICE_STARTED_FIRE_AT_SHOT',
                     'DEVICE_STARTED_FIRE_AT_RAMMING', 'TANKMAN_HIT_AT_SHOT', 'DEATH_FROM_DEVICE_EXPLOSION_AT_SHOT',
                     'DEVICE_CRITICAL_AT_FIRE', 'DEVICE_DESTROYED_AT_FIRE', 'DEVICE_REPAIRED_TO_CRITICAL',
                     'DEVICE_REPAIRED', 'TANKMAN_RESTORED', 'DEATH_FROM_DEVICE_EXPLOSION_AT_FIRE',
                     'ENGINE_CRITICAL_AT_UNLIMITED_RPM', 'ENGINE_DESTROYED_AT_UNLIMITED_RPM',
                     'DEATH_FROM_SHOT', 'DEATH_FROM_INACTIVE_CREW_AT_SHOT', 'DEATH_FROM_RAMMING',
                     'DEATH_FROM_FIRE', 'DEATH_FROM_INACTIVE_CREW', 'FIRE_STOPPED')
DAMAGE_INFO_INDICES = dict((x[1], x[0]) for x in enumerate(DAMAGE_INFO_CODES))
CLIENT_INACTIVITY_TIMEOUT = 40

class CHAT_LOG:
    NONE = 0
    MESSAGES = 1
    ACTIONS = 2


CHAT_MESSAGE_MAX_LENGTH = 512
VEHICLE_CLASSES = ('lightTank', 'mediumTank', 'heavyTank', 'SPG', 'AT-SPG')
VEHICLE_CLASS_INDICES = dict((x[1], x[0]) for x in enumerate(VEHICLE_CLASSES))
MAX_VEHICLE_LEVEL = 10

class QUEUE_TYPE:
    RANDOMS = 1
    COMPANIES = 2
    VOLUNTEERS = 3


USER_ACTIVE_CHANNELS_LIMIT = 50

class INVOICE_EMITTER:
    PAYMENT_SYSTEM = 1
    BACKYARD = 2
    COMMUNITY = 3
    PORTAL = 4
    NEGATIVE = (
     BACKYARD, COMMUNITY, PORTAL)
    RANGE = (
     PAYMENT_SYSTEM, BACKYARD, COMMUNITY, PORTAL)


class INVOICE_ASSET:
    GOLD = 1
    CREDITS = 2
    PREMIUM = 3
    DATA = 4


CHANNEL_SEARCH_RESULTS_LIMIT = 50
USER_SEARCH_RESULTS_LIMIT = 50

class USER_SEARCH_MODE:
    ALL = 0
    ONLINE = 1
    OFFLINE = 2


class AOGAS_TIME:
    REDUCED_GAIN = 10200
    NO_GAIN = 17400
    RESET = 18000


SERVER_BAD_WORDS_FILTER = False

class SERVER_BAD_WORDS_FILTER_MODE:
    ACCOUNT = 1
    CHANNEL = 2


CURRENT_SERVER_BAD_WORDS_FILTER_MODE = SERVER_BAD_WORDS_FILTER_MODE.CHANNEL

class CREDENTIALS_RESTRICTION:
    BASIC = 0
    CHINESE = 1


CREDENTIALS_RESTRICTION_SET = CREDENTIALS_RESTRICTION.BASIC if not IS_CHINA else CREDENTIALS_RESTRICTION.CHINESE

class AUTO_MAINTENANCE_TYPE:
    REPAIR = 1
    LOAD_AMMO = 2
    EQUIP = 3


class AUTO_MAINTENANCE_RESULT:
    OK = 0
    NOT_ENOUGH_ASSETS = 1


class REQUEST_COOLDOWN:
    PLAYER_DOSSIER = 1.0
    PLAYER_CLAN_INFO = 1.0
    PREBATTLE_CREATION = 4.0
    PREBATTLE_NOT_READY = 2.0
    PREBATTLE_TEAM_NOT_READY = 1.0
    PREBATTLE_JOIN = 1.0


class CAPTCHA_API:
    RE_CAPTCHA = 1
    KONG = 2


CURRENT_CAPTCHA_API = CAPTCHA_API.RE_CAPTCHA
return
